sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn deploy

after_success:
  - yarn codecov
